# Generated by Django 4.2.4 on 2024-04-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_is_customer_user_is_listener'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_artist',
            field=models.BooleanField(verbose_name='Is Artist'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_listener',
            field=models.BooleanField(verbose_name='Is Listener'),
        ),
    ]
