# Generated by Django 4.2.4 on 2024-04-05 17:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('audiogramAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audio',
            options={'ordering': ('title', 'genre', 'producer', 'published'), 'verbose_name_plural': 'Audios'},
        ),
        migrations.AddField(
            model_name='album',
            name='published',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
