# Generated by Django 4.2.4 on 2024-04-06 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audiogramAPI', '0002_alter_audio_options_album_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('audios', models.ManyToManyField(related_name='playlist_audios', to='audiogramAPI.audio')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Playlists',
            },
        ),
    ]
