# Generated by Django 4.2.4 on 2024-04-07 23:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audiogramAPI', '0003_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
